version: "3"

services:
  express-app:
    image: express-app
    container_name: express-app
    ports:
      - 5000:5000
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=5000
    # env_file:
    #   - ./.env